##Independent project##
In this weeks independent project, you will be working as a data scientist working for an electric car-sharing service company. You have been tasked to process stations data to understand electric car usage over time by solving for the following research question;

##Research Question##

Identify the most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018.
Bonus Questions (Optional)

What is the most popular hour for returning cars?
What station is the most popular?
Overall?
At the most popular picking hour?
What postal code is the most popular for picking up Blue cars? Does the most popular station belong to that postal code?
Overall?
At the most popular picking hour?
Do the results change if you consider Utilib and Utilib 1.4 instead of Blue cars?

In [0]:
#
# ---------
#

# Importing our Modules


> Importing our pandas modue as pd.

In [0]:
# Importing pandas
#
import pandas as pd

# Importing our Csv files and creating our dataset.

In [12]:
url = "Autolib_dataset.csv"
df = pd.read_csv(url)
df.head()

                              Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23

[5 rows x 25 columns]

# View our data info

In [13]:
# Getting information from our dataset.
#
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar counter      5000 non-null   int64
 3   Utilib counter       5000 non-null   int64
 4   Utilib 1.4 counter   5000 non-null   int64
 5   Charge Slots         5000 non-null   int64
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots                5000 non-null   int64
 17  Station type         5000 non-null   object
 18  Status               5000 non-null   object
 19  Subscription status  5000 non-null   object
 20  year                 5000 non-null   int64
 21  month                5000 non-null   int64
 22  day                  5000 non-null   int64
 23  hour                 5000 non-null   int64
 24  minute               5000 non-null   int64
dtypes: int64(12), object(13)
memory usage: 976.7+ KB

In [14]:
# Describing our data allows us to get a general overview of how the data is.
#
df.describe()

              Cars  Bluecar counter  ...         hour       minute
count  5000.000000      5000.000000  ...  5000.000000  5000.000000
mean      2.333600         2.333600  ...    11.509200    29.270000
std       2.035274         2.035274  ...     6.893549    17.231741
min       0.000000         0.000000  ...     0.000000     0.000000
25%       0.000000         0.000000  ...     6.000000    14.000000
50%       2.000000         2.000000  ...    11.000000    29.000000
75%       4.000000         4.000000  ...    18.000000    44.000000
max       7.000000         7.000000  ...    23.000000    59.000000

[8 rows x 12 columns]

# Data Preparation/Cleaning

># 1.1 Validity

In [0]:
# Procedure 1:
# Data Cleaning Action: Droping the irrelevant Scheduled at column
# Explanation: We are droping it since its not useful in our analysis.
#
df_new = df.drop(['Scheduled at'], axis=1, inplace=True)
df_new

In [0]:
# Procedure 2:
# Data Cleaning Action: Droping the irrelevant Subscription status at column
# Explanation: We are droping it since its not useful in our analysis.
#
df_new = df.drop(['Subscription status'], axis=1, inplace=True)
df_new

In [0]:
# Procedure 3:
# Data Cleaning Action: Droping the irrelevant Subscription status at column
# Explanation: We are droping it since its not useful in our analysis.
#
df_new = df.drop(['Status'], axis=1, inplace=True)
df_new

In [0]:
# Procedure 3:
# Data Cleaning Action: Droping the Displayed comment column
# Explanation: We are droping it since its not useful in our analysis.
#
df_new = df.drop(['Displayed comment'], axis=1, inplace=True)
df_new

># 1.2 Accuracy

In [19]:
# Procedure 1:
# Data Cleaning Action: Checking for null values in our dataset.
# Explanation: This is to allows us to determin the columns that have null values.
# 
df_null = df.isnull().any()
df_null

Address               False
Cars                  False
Bluecar counter       False
Utilib counter        False
Utilib 1.4 counter    False
Charge Slots          False
Charging Status       False
City                  False
ID                    False
Kind                  False
Geo point             False
Postal code           False
Public name           False
Rental status         False
Slots                 False
Station type          False
year                  False
month                 False
day                   False
hour                  False
minute                False
dtype: bool

># 1.3 Completeness

In [20]:
# Procedure 1:
# Data Cleaning Action: Check for duplicate values.
# Explanation: This is to allow us determine data that is duplicated.
#
df_dup = df.duplicated().sum()
df_dup

0

># 1.4 Consistency

In [21]:
# Procedure 1:
# Data Cleaning Action: Dropping null values if they exist.
# Explanation: This is to allow us determine data that is duplicated.
#
df_new = df.dropna(how="all")
df_new.head()

                              Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23

[5 rows x 21 columns]

># 1.5 Uniformity

In [22]:
# Procedure 1:
# Data Cleaning Action: Converting column names to lowercase characters.
# Explanation: This is to allow for a uniform columns in the dataframe.
#
df.columns = df.columns.str.rstrip().str.lower()
df.head(3)

                            address  cars  bluecar counter  ...  day  hour  minute
0               2 Avenue de Suffren     0                0  ...    8    11      43
1         145 Rue Raymond Losserand     6                6  ...    6     7      24
2  2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14

[3 rows x 21 columns]

In [23]:
# Procedure 2:
# Data Cleaning Action: Converting row values to lowercase characters.
# Explanation: This is to allow for rows to have uniform values which are in lowercase in the dataframe.
#
df = df.astype(str).apply(lambda x: x.str.lower())
df.head(3)

                            address cars bluecar counter  ... day hour minute
0               2 avenue de suffren    0               0  ...   8   11     43
1         145 rue raymond losserand    6               6  ...   6    7     24
2  2 avenue john fitzgerald kennedy    3               3  ...   3   20     14

[3 rows x 21 columns]

In [24]:
df.columns = df.columns.str.replace(" ", "_", regex=True)
df.head(2)

                     address cars bluecar_counter  ... day hour minute
0        2 avenue de suffren    0               0  ...   8   11     43
1  145 rue raymond losserand    6               6  ...   6    7     24

[2 rows x 21 columns]

In [0]:
# Splitting the geopoint column into two.
#

# Exporting our clean csv file.

In [0]:
df.to_csv("autolib_clean.csv")

# Answering Questions

#  *Using Blue cars*

> # *Challenge 1*
> 1. What is the most popular hour for returning cars?

In [65]:
# Challenge 1
# Finding the most popular hour for returning cars?.
#
url = "autolib_clean.csv"
df = pd.read_csv(url)
df_x = df[["bluecar_counter","day", "hour", "minute"]]
df_car = df_x[df_x["bluecar_counter"] == 0]
df_car['hour'].max()

23

> # *Challenge 2*
>  What station is the most popular?
      > * Overall?

In [66]:
# Challenge 2
# Finding the most popular station( Overall) from our dataset.
#
df_p = df.groupby(['address'])['bluecar_counter'].sum().sort_values(ascending=False)
df_p.head(1)

address
32 rue robert marchand    50
Name: bluecar_counter, dtype: int64

> # *Challenge 3*
> 3. What station is the most popular?
      > * At the most popular picking hour?

In [67]:
# Challenge 3
# Finding the most popular station (At the most popular picking hour) from our dataset.
#
df_p = df.groupby(['address'])['hour'].max().sort_values(ascending=False)

df_p.head(1)

address
11 rue robert lavergne    23
Name: hour, dtype: int64

> # *Challenge 4*
  > 4. What postal code is the most popular for picking up Blue cars? Does the most popular station belong to that postal code?
   > * Overall?

In [68]:
# Challenge 4
# Finding the What postal code is the most popular for picking up Blue cars? 
# Does the most popular station belong to that postal code? from our dataset.
#
df_station = df[['address', 'postal_code', 'bluecar_counter']]
df_postal = df_station.sort_values('bluecar_counter', ascending=False)
df_postal.head(1)

                       address  postal_code  bluecar_counter
1985  99 rue charles-de-gaulle        91330                7

 > # *Challenge 5*
   > * At the most popular picking hour?

In [69]:
# Challenge 5
# Finding the What postal code is the most popular for picking up Blue cars? 
# Does the most popular station belong to that postal code? from our dataset.
#
df_station = df[['address', 'postal_code', 'hour']]
df_postal = df_station.sort_values('hour', ascending=False)
df_postal.head(1)

                    address  postal_code  hour
581  65 boulevard de picpus        75012    23

> # *Challenge 6*
> 5. Sorting the non-existent, operational and broken charging status in Descending Order.

In [70]:
# Challenge 4
# Finding the What charging status has the highest value for picking up Blue cars from our dataset.
#
df_city = df.groupby(['charging_status'])['bluecar_counter'].sum().sort_values(ascending=False)
df_city.head(16)

charging_status
nonexistent    7269
operational    4359
broken           40
Name: bluecar_counter, dtype: int64

> # Using Utilib counter and Utilib 1.4 counter

> # *Challenge 1*
>  What station is the most popular?
      > * Overall?

> a). utilib_counter

In [71]:
# Challenge 1.1
# Finding the most popular station( Overall) from our dataset.
#
df_p = df.groupby(['address'])['utilib_counter'].sum().sort_values(ascending=False)
df_p.head(1)

address
5 avenue mac mahon    4
Name: utilib_counter, dtype: int64

> b). utilib_1.4_counter

In [72]:
# Challenge 1.2
# Finding the most popular station( Overall) from our dataset.
#
df_p = df.groupby(['address'])['utilib_1.4_counter'].sum().sort_values(ascending=False)
df_p.head(1)

address
123 grande rue    9
Name: utilib_1.4_counter, dtype: int64

> # *Challenge 2*
  > 2. What postal code is the most popular for picking up Utilib_counter and Utilib_1.4_counter? Does the most popular station belong to that postal code?
   > * Overall?

> b). utilib_1.4_counter

In [73]:
# Challenge 2.1
# Finding the What postal code is the most popular for picking up Blue cars? 
# Does the most popular station belong to that postal code? from our dataset.
#
df_station = df[['address', 'postal_code', 'utilib_counter']]
df_postal = df_station.sort_values('utilib_counter', ascending=False)
df_postal.head(1)

                      address  postal_code  utilib_counter
3329  19 rue de chateaubriand        75008               2

> b). utilib_1.4_counter

In [74]:
# Challenge 2.2
# Finding the What postal code is the most popular for picking up Blue cars? 
# Does the most popular station belong to that postal code? from our dataset.
#
df_station = df[['address', 'postal_code', 'utilib_1.4_counter']]
df_postal = df_station.sort_values('utilib_1.4_counter', ascending=False)
df_postal.head(1)

             address  postal_code  utilib_1.4_counter
2731  123 grande rue        92310                   3

> # *Challenge 3*
> 5. Sorting the non-existent, operational and broken charging status in Descending Order.

> b). utilib_1.4_counter

In [75]:
# Challenge 3.1
# Finding the What charging status has the highest value for picking up utilib cars from our dataset.
#
df_city = df.groupby(['charging_status'])['utilib_counter'].sum().sort_values(ascending=False)
df_city

charging_status
nonexistent    178
operational    120
broken           0
Name: utilib_counter, dtype: int64

> b). utilib_1.4_counter

In [76]:
# Challenge 4
# Finding the What charging status has the highest value for picking up Blue cars from our dataset.
#
df_city = df.groupby(['charging_status'])['utilib_1.4_counter'].sum().sort_values(ascending=False)
df_city

charging_status
nonexistent    363
operational    248
broken           4
Name: utilib_1.4_counter, dtype: int64

# Research Question

> * Identify the most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018.*

In [38]:
df_p = df[['city', 'bluecar_counter', 'hour']]
df_paris = df[df['city'] == 'paris']
df_p = df_paris.groupby(['bluecar_counter'])['hour'].max().sort_values(ascending=False)
df_p

bluecar_counter
6    23
5    23
4    23
3    23
2    23
1    23
0    23
7    17
Name: hour, dtype: int64